SELECT CUSTOMER.CUSTNAME, CUSTOMER.CITY, SALESMAN.NAME, SALESMAN.CITY, DEAL.AMOUNT
FROM CUSTOMER
JOIN SALESMAN ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
JOIN DEAL ON CUSTOMER.CUSTOMER_ID = DEAL.CUSTOMER_ID AND DEAL.AMOUNT > 10000;

SELECT CUSTOMER.CUSTNAME
FROM CUSTOMER
JOIN DEAL ON DEAL.DATE_DEAL BETWEEN '01-01-17' AND '31-12-18' AND CUSTOMER.CUSTOMER_ID = DEAL.CUSTOMER_ID
GROUP BY CUSTOMER.CUSTNAME;

--Запросы на поиск по всем таблицам
--имя лучшего менеджера по продажам по сумме сделок за август 2017 года
SELECT NAME, SUM_DEAL
FROM
--таблица суммы продаж по менеджерам
  (SELECT SALESMAN.NAME, SUM(DEAL.AMOUNT) SUM_DEAL
  FROM SALESMAN
  JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
    JOIN DEAL ON CUSTOMER.CUSTOMER_ID = DEAL.CUSTOMER_ID
    WHERE DEAL.DATE_DEAL BETWEEN '01.08.17' AND '31.08.17'
    GROUP BY SALESMAN.NAME)
WHERE
--макс значение из таблицы суммы продаж по менеджерам
  SUM_DEAL = (
      SELECT MAX(SUM_DEAL1)
        FROM
          (SELECT SALESMAN.NAME, SUM(DEAL.AMOUNT) SUM_DEAL1
            FROM SALESMAN
            JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
              JOIN DEAL ON CUSTOMER.CUSTOMER_ID = DEAL.CUSTOMER_ID
              WHERE DEAL.DATE_DEAL BETWEEN '01.08.17' AND '31.08.17'
              GROUP BY SALESMAN.NAME));