CREATE TABLE FORUM_POLLS_OPTIONS_VOTES (
ID INT,
CONSTRAINT ID_PK_FPOV PRIMARY KEY (ID),
ID_POLL_OPTION INT,
CONSTRAINT ID_POLL_OPTION_FK FOREIGN KEY(ID_POLL_OPTION) REFERENCES FORUM_POLL_OPTIONS(ID),
ID_USER INT,
CONSTRAINT ID_USER_FK FOREIGN KEY(ID_USER) REFERENCES USERS(ID),
DATE_FORUM_POLLS_OPTIONS_VOTES TIMESTAMP,
IP VARCHAR(20)
);