CREATE TABLE FORUM_POSTS (
ID INT,
CONSTRAINT ID_PK_POST PRIMARY KEY (ID),
ID_SUBCATEGORY INT,
CONSTRAINT ID_SUBCATEGORY_FK FOREIGN KEY(ID_SUBCATEGORY) REFERENCES FORUM_SUBCATEGORIES(ID),
ID_USER INT,
CONSTRAINT ID_USER FOREIGN KEY(ID_USER) REFERENCES USERS(ID),
PARENT_POST INT,
CONSTRAINT PARENT_POST_FK FOREIGN KEY(PARENT_POST) REFERENCES FORUM_POSTS(ID),
TITLE VARCHAR(90),
CONTENT BLOB,
IS_POLL CHAR(1),
DATE_POST TIMESTAMP,
IP VARCHAR(20)
);