CREATE TABLE FORUM_SUBCATEGORIES (
ID INT,
CONSTRAINT ID_PK2 PRIMARY KEY (ID),
ID_CATEGORY INT,
CONSTRAINT ID_CATEGORY_FK FOREIGN KEY(ID_CATEGORY) REFERENCES FORUM_CATEGORIES(ID),
TITLE VARCHAR(45),
DESCRIPTION NVARCHAR2(200),
DATE_CATEGORY TIMESTAMP,
IP VARCHAR(20)
);