CREATE TABLE FORUM_POLL_OPTIONS (
ID INT,
CONSTRAINT ID_PK_FPO PRIMARY KEY (ID),
ID_POST INT,
CONSTRAINT ID_POST_FK FOREIGN KEY(ID_POST) REFERENCES FORUM_POSTS(ID),
TITLE VARCHAR(64),
DATE_FORUM_POLL_OPTIONS TIMESTAMP
);