CREATE TABLE SALESMAN (
  SALESMAN_ID NUMBER PRIMARY KEY,
  NAME NVARCHAR2(50) NOT NULL,
  CITY NVARCHAR2(50) NOT NULL,
  COMISSION NUMBER(*,2) DEFAULT '0,1'
);

CREATE TABLE CUSTOMER (
  CUSTOMER_ID NUMBER PRIMARY KEY,
  CUSTNAME NVARCHAR2(50) NOT NULL,
  CITY NVARCHAR2(50) NOT NULL,
  SALESMAN_ID NUMBER,
  CONSTRAINT SALESMAN_FK FOREIGN KEY (SALESMAN_ID) REFERENCES SALESMAN(SALESMAN_ID)
);

INSERT INTO SALESMAN VALUES (5001, '1 1', 'New York', 0.15);
INSERT INTO SALESMAN VALUES (5002, '2 2', 'Paris', 0.13);
INSERT INTO SALESMAN VALUES (5005, '3 3', 'London', 0.11);
INSERT INTO SALESMAN VALUES (5006, '4 4', 'Paris', 0.14);
INSERT INTO SALESMAN VALUES (5003, '5 5', 'London', 0.12);
INSERT INTO SALESMAN VALUES (5007, '6 6', 'Nikisia', 0.15);
INSERT INTO SALESMAN VALUES (5008, '7 7', 'Kiev', 0.17);
INSERT INTO SALESMAN VALUES (5009, '8 8', 'Moscow', 0.29);

INSERT INTO CUSTOMER VALUES (3002, 'W W', 'New York', 5001);
INSERT INTO CUSTOMER VALUES (3005, 'F F', 'California', 5002);
INSERT INTO CUSTOMER VALUES (3001, 'V V', 'London', 5005);
INSERT INTO CUSTOMER VALUES (3004, 'GGG G', 'Paris', 5006);
INSERT INTO CUSTOMER VALUES (3009, 'T YY', 'Berlin', 5003);
INSERT INTO CUSTOMER VALUES (3008, 'SS FF', 'London', 5002);
INSERT INTO CUSTOMER VALUES (3007, 'SD CF', 'New York', 5001);
INSERT INTO CUSTOMER VALUES (3003, '5T H', 'Moscow', 5007);
INSERT INTO CUSTOMER VALUES (3010, 'TT JJW', 'Kiev', null);

SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME
FROM SALESMAN, CUSTOMER
WHERE SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID;

SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID;

SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME, SALESMAN.CITY
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.CITY = CUSTOMER.CITY;