CREATE TABLE PRODUCTS (
PRODUCT_ID NUMBER,
CONSTRAINT PRODUCT_ID_PK PRIMARY KEY(PRODUCT_ID),

PRODUCT_NAME NVARCHAR2(50),

SUPPLIERS_ID NUMBER,
CONSTRAINT SUPPLIERS_ID_FK FOREIGN KEY(SUPPLIERS_ID) REFERENCES SUPPLIERS(SUPPLIERS_ID),

CATEGORY_ID NUMBER,
CONSTRAINT CATEGORY_ID_FK FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID),

QUANTITY_PER_UNIN NUMBER,
UNITE_PRICE NUMBER(8,2),
UNITS_IN_STOCK NUMBER,
UNITE_ON_ORDER NUMBER,
REORDER_LEVEL NUMBER,
DISCONTINUED NVARCHAR2(50)
);